/*datos del creador del sitio*/
function cartel() {
    alert(
        "Carla Romero Albornoz - Tel: 2613865991 - Email: cromeroalbornoz@outlook.com"
    )}

/*modo oscuro*/
function inclusivo() {
        /*nav*/
        document.getElementById("nav").style.backgroundColor="#7B241C";
        document.getElementById("enlace1").style.backgroundColor="#7B241C";
        document.getElementById("enlace2").style.backgroundColor="#7B241C";
        document.getElementById("enlace3").style.backgroundColor="#7B241C";
        document.getElementById("enlace4").style.backgroundColor="#7B241C";
        document.getElementById("enlace5").style.backgroundColor="#7B241C";
        document.getElementById("enlace6").style.backgroundColor="#7B241C";
        document.getElementById("enlace7").style.backgroundColor="#7B241C";
        document.getElementById("enlace1").style.color="#CD6155";
        document.getElementById("enlace2").style.color="#CD6155";
        document.getElementById("enlace3").style.color="#CD6155";
        document.getElementById("enlace4").style.color="#CD6155";
        document.getElementById("enlace5").style.color="#CD6155";
        document.getElementById("enlace6").style.color="#CD6155";
        document.getElementById("enlace7").style.color="#CD6155";
        /*body*/
        document.body.style.backgroundImage="none";
        document.body.style.backgroundColor="black";
        /*footer*/
        document.getElementById("footer").style.backgroundColor="#7B241C";
        document.getElementById("developer").style.backgroundColor="#7B241C";
        document.getElementById("developer").style.borderColor="#CD6155";
        document.getElementById("developer").style.color="#CD6155";
        /*main*/
        document.getElementById("section").style.backgroundColor="#212121";
        document.getElementById("aside").style.backgroundColor="#212121";
        document.getElementById("article").style.backgroundColor="#212121";
        document.getElementById("section").style.color="#F2F4F4";
        document.getElementById("aside").style.color="#F2F4F4";
        document.getElementById("article").style.color="#F2F4F4";
        /*cards*/
        document.getElementById("card1-titulo").style.backgroundColor="#212121";
        document.getElementById("card1-parrafo").style.backgroundColor="#212121";
        document.getElementById("card2-titulo").style.backgroundColor="#212121";
        document.getElementById("card2-parrafo").style.backgroundColor="#212121";
        document.getElementById("card3-titulo").style.backgroundColor="#212121";
        document.getElementById("card3-parrafo").style.backgroundColor="#212121";
        document.getElementById("card4-titulo").style.backgroundColor="#212121";
        document.getElementById("card4-parrafo").style.backgroundColor="#212121";
        document.getElementById("card1-parrafo").style.color="#F2F4F4";
        document.getElementById("card2-parrafo").style.color="#F2F4F4";
        document.getElementById("card3-parrafo").style.color="#F2F4F4";
        document.getElementById("card4-parrafo").style.color="#F2F4F4";
        document.getElementById("card1").style.backgroundColor="#F2F4F4";
        document.getElementById("card2").style.backgroundColor="#F2F4F4";
        document.getElementById("card3").style.backgroundColor="#F2F4F4";
        document.getElementById("card4").style.backgroundColor="#F2F4F4";
        /*
        document.body.style.backgroundColor="black";
        document.getElementById("origen").style.color="gray";
        document.getElementById("epi").style.color="white";
        document.getElementById("cocinar").style.color="grey";
        document.getElementById("ingredientes").style.color="white";
        document.getElementById("masa").style.color="white";
        document.getElementById("relleno").style.color="white";
        document.getElementById("salsa").style.color="white";
        document.getElementById("procedimiento").style.color="white";
        document.getElementById("lamasa").style.color="white";
        document.getElementById("elrelleno").style.color="white";
        document.getElementById("formar").style.color="white";
        document.getElementById("infoa").style.color="grey";
        document.getElementById("parrafo").style.color="white";
        */
        /*
        document.getElementById("aleman").style.backgroundColor="black";
        document.getElementById("tiramisu").style.backgroundColor="black";
        document.getElementById("lemon").style.backgroundColor="black";
        document.getElementById("cheesecake").style.backgroundColor="black";
        document.getElementById("turrontitulo").style.color="grey";
        document.getElementById("turronparrafo").style.color="white";
        document.getElementById("tiramisutitulo").style.color="grey";
        document.getElementById("tiramisuparrafo").style.color="white";
        document.getElementById("lemontitulo").style.color="grey";
        document.getElementById("lemonparrafo").style.color="white";
        document.getElementById("caketitulo").style.color="grey";
        document.getElementById("cakeparrafo").style.color="white";
        */
        }
